#!/bin/bash
# OpenRY one-click installer
# Detects Python environment and installs openry to PATH
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}=== OpenRY Installer ===${NC}"

# --- 1. Find Python ---
PYTHON=""
for candidate in python3.12 python3.11 python3.10 python3.9 python3; do
    if command -v "$candidate" &>/dev/null; then
        PYTHON="$candidate"
        break
    fi
done

if [ -z "$PYTHON" ]; then
    echo -e "${RED}Error: Python 3 not found.${NC}"
    echo "Install via one of:"
    echo "  macOS:  brew install python@3.12"
    echo "  Linux:  sudo apt install python3  (or your distro's package manager)"
    echo "  Windows: winget install Python.Python.3.12"
    exit 1
fi

PY_VER=$($PYTHON --version 2>&1)
echo -e "Using: ${GREEN}$PY_VER${NC}"

# --- 2. Install pyyaml ---
echo "Installing pyyaml..."
$PYTHON -m pip install pyyaml --quiet 2>/dev/null || {
    echo -e "${YELLOW}pip install pyyaml failed, continuing anyway...${NC}"
}

# --- 3. Try pip install ---
PIP_OK=false
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

if $PYTHON -m pip install -e . --quiet 2>/dev/null; then
    if command -v openry &>/dev/null; then
        echo -e "${GREEN}✓ Installed via pip (editable mode)${NC}"
        PIP_OK=true
    fi
fi

# --- 4. Fallback: wrapper script ---
if [ "$PIP_OK" = false ]; then
    WRAPPER_DIR="${HOME}/.local/bin"
    mkdir -p "$WRAPPER_DIR"

    cat > "$WRAPPER_DIR/openry" << WRAPPER
#!/bin/bash
# Auto-generated by OpenRY installer
OPENRY_HOME="\${OPENRY_HOME:-$SCRIPT_DIR}"
cd "\$OPENRY_HOME" && PYTHONPATH="\$OPENRY_HOME" $PYTHON -m openry "\$@"
WRAPPER
    chmod +x "$WRAPPER_DIR/openry"

    echo -e "${GREEN}✓ Wrapper installed to ${WRAPPER_DIR}/openry${NC}"

    # Add to PATH if not already
    if [[ ":$PATH:" != *":$WRAPPER_DIR:"* ]]; then
        SHELL_RC=""
        case "$SHELL" in
            */zsh)  SHELL_RC="$HOME/.zshrc" ;;
            */bash) SHELL_RC="$HOME/.bashrc" ;;
            *)      SHELL_RC="$HOME/.profile" ;;
        esac
        echo "export PATH=\"$WRAPPER_DIR:\$PATH\"" >> "$SHELL_RC"
        echo -e "${YELLOW}  Added to PATH in $SHELL_RC — restart your shell or run:${NC}"
        echo "  source $SHELL_RC"
    fi
fi

# --- 5. Verify ---
export PATH="$HOME/.local/bin:$PATH"
echo ""
if openry -c 'echo "install OK"' 2>/dev/null | grep -q "install OK"; then
    echo -e "${GREEN}✓ openry is ready!${NC}"
    echo ""
    echo "  Quick test:  openry -c 'echo hello'"
    echo "  With env:    OPENRY_RUN_ID=xxx openry --status completed"
else
    echo -e "${RED}✗ Verification failed. Try manually:${NC}"
    echo "  cd $SCRIPT_DIR && PYTHONPATH=. $PYTHON -m openry -c 'echo test'"
fi
