#!/usr/bin/env bash
# ============================================================================
# OpenRY — One-Click Cross-Platform Installer
# ============================================================================
# Platforms:
#   macOS   ✅  (primary, tested on Apple Silicon + Intel)
#   Linux   ✅  (supported)
#   Windows ✅  (install.ps1 — see that file)
#
# Windows users — install manually for now:
#   1. Install Python 3.9+:  winget install Python.Python.3.12
#   2. cd openry && pip install -e .
#   3. set OPENRY_HOME=%USERPROFILE%\.openry
#
# License: MIT — OpenRY Contributors
# ============================================================================
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ── Parse arguments ───────────────────────────────────────────────────
SKIP_PYTHON=false
SKIP_PLUGIN=false

for arg in "$@"; do
    case "$arg" in
        --skip-python)   SKIP_PYTHON=true ;;
        --skip-plugin)   SKIP_PLUGIN=true ;;
        --help|-h)
            echo "Usage: bash install.sh [--skip-python] [--skip-plugin]"
            echo ""
            echo "Options:"
            echo "  --skip-python   Skip Python detection and pip install"
            echo "  --skip-plugin   Skip orchestrator-plugin (OpenClaw) installation"
            exit 0
            ;;
    esac
done

echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║       OpenRY — One-Click Installer  ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════╝${NC}"
echo ""

# ── 1. OS Detection ──────────────────────────────────────────────────────

OS="$(uname -s)"
case "$OS" in
    Darwin)  OS_NAME="macOS" ;;
    Linux)   OS_NAME="Linux" ;;
    *)
        echo -e "${RED}✗ Unsupported OS: $OS${NC}"
        echo ""
        echo "OpenRY currently supports macOS and Linux."
        echo "Windows support is planned — for now, install manually:"
        echo "  1. Install Python 3.9+:  winget install Python.Python.3.12"
        echo "  2. cd openry && pip install -e ."
        echo "  3. set OPENRY_HOME=%USERPROFILE%\\.openry"
        exit 1
        ;;
esac
echo -e "  Detected OS: ${CYAN}$OS_NAME${NC}"

# ── 2. Resolve paths ─────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WRAPPER_BIN="${HOME}/.local/bin"
OPENRY_HOME="${OPENRY_HOME:-$HOME/.openry}"

echo -e "  Install dir: ${CYAN}$SCRIPT_DIR${NC}"
echo ""

# ── 3. Python Detection ───────────────────────────────────────────────────

if [ "$SKIP_PYTHON" = true ]; then
    echo -e "  ${YELLOW}⚠ Skipping Python check (--skip-python)${NC}"
    PYTHON="python3"
else

PYTHON=""
for candidate in python3.12 python3.11 python3.10 python3.9 python3; do
    if command -v "$candidate" &>/dev/null; then
        PYTHON="$candidate"
        break
    fi
done

if [ -z "$PYTHON" ]; then
    echo -e "${RED}✗ Python 3.9+ not found.${NC}"
    echo ""
    echo "Install Python 3 first:"
    echo "  macOS:  brew install python@3.12"
    echo "  Linux:  sudo apt install python3"
    exit 1
fi

PY_VER=$($PYTHON --version 2>&1)
echo -e "  ${GREEN}✓${NC} Python: $PY_VER"

fi  # SKIP_PYTHON

# ── 4. pip Detection ──────────────────────────────────────────────────────

if [ "$SKIP_PYTHON" != true ]; then
if ! $PYTHON -m pip --version &>/dev/null; then
    echo -e "${RED}✗ pip not available for $PYTHON${NC}"
    echo "  macOS:  $PYTHON -m ensurepip --upgrade"
    echo "  Linux:  sudo apt install python3-pip"
    exit 1
fi
fi

# ── 5. Install pyyaml dependency ──────────────────────────────────────────

echo -e "  Installing pyyaml..."
$PYTHON -m pip install pyyaml --quiet 2>/dev/null || {
    echo -e "  ${YELLOW}⚠ pyyaml install failed (non-fatal, continuing...)${NC}"
}

# ── 6. Install openry CLI ─────────────────────────────────────────────────

echo -e "  Installing openry CLI..."
PIP_OK=false
cd "$SCRIPT_DIR"

# Strategy A: pip install --user (puts openry in ~/.local/bin, no sudo)
if $PYTHON -m pip install --user -e . --quiet 2>/dev/null; then
    mkdir -p "$WRAPPER_BIN"
    export PATH="$WRAPPER_BIN:$PATH"

    if command -v openry &>/dev/null; then
        PIP_OK=true
    else
        # pip may have put it in ~/Library/Python/3.x/bin (macOS default)
        OPENRY_PATH=$($PYTHON -c "import shutil; print(shutil.which('openry') or '')" 2>/dev/null || true)
        if [ -n "$OPENRY_PATH" ] && [ -x "$OPENRY_PATH" ]; then
            PIP_OK=true
        fi
    fi
fi

# Strategy B: fallback — create a wrapper script
if [ "$PIP_OK" = false ]; then
    mkdir -p "$WRAPPER_BIN"

    cat > "$WRAPPER_BIN/openry" << WRAPPER
#!/usr/bin/env bash
# Auto-generated by OpenRY installer
OPENRY_HOME="\${OPENRY_HOME:-$OPENRY_HOME}"
PYTHONPATH="$SCRIPT_DIR:\$PYTHONPATH" exec $PYTHON -m openry "\$@"
WRAPPER
    chmod +x "$WRAPPER_BIN/openry"
    export PATH="$WRAPPER_BIN:$PATH"
    echo -e "  ${YELLOW}⚠ Using wrapper at ${WRAPPER_BIN}/openry${NC}"
else
    echo -e "  ${GREEN}✓${NC} openry installed via pip"
fi

# ── 7. Ensure ~/.local/bin in shell PATH ─────────────────────────────────

SHELL_RC=""
case "${SHELL##*/}" in
    zsh)  SHELL_RC="$HOME/.zshrc" ;;
    bash) SHELL_RC="${HOME}/.bashrc" ;;
    *)    SHELL_RC="${HOME}/.profile" ;;
esac

if [ -f "$SHELL_RC" ] && grep -qF "$WRAPPER_BIN" "$SHELL_RC" 2>/dev/null; then
    : # already configured
else
    {
        echo ""
        echo "# Added by OpenRY installer"
        echo "export OPENRY_HOME=\"${OPENRY_HOME}\""
        echo "export PATH=\"$WRAPPER_BIN:\$PATH\""
    } >> "$SHELL_RC"
    echo -e "  ${YELLOW}⚠ Added ${WRAPPER_BIN} + OPENRY_HOME to ${SHELL_RC}${NC}"
    echo "    Restart your terminal or run: source $SHELL_RC"
fi

# ── 8. Initialize .openry/ from seed ──────────────────────────────────────

SEED_DIR="${SCRIPT_DIR}/seed"
if [ -d "$SEED_DIR" ]; then
    cp -r "$SEED_DIR"/* "$OPENRY_HOME/" 2>/dev/null || true
    WF_COUNT=$(ls "$OPENRY_HOME/workflows/"*.yaml 2>/dev/null | wc -l | tr -d ' ')
    CP_COUNT=$(ls "$OPENRY_HOME/compositions/"*.yaml 2>/dev/null | wc -l | tr -d ' ')
    PM_COUNT=$(ls "$OPENRY_HOME/prompts/"*.md 2>/dev/null | wc -l | tr -d ' ')
    echo -e "  ${GREEN}✓${NC} Initialized ${CYAN}${OPENRY_HOME}${NC} from seed/"
    echo "    workflows: ${WF_COUNT} files, compositions: ${CP_COUNT} files, prompts: ${PM_COUNT} files"
else
    # Fallback: create empty structure
    mkdir -p "$OPENRY_HOME/workflows" "$OPENRY_HOME/compositions" "$OPENRY_HOME/prompts" "$OPENRY_HOME/prompt_blocks"
    echo -e "  ${YELLOW}⚠ seed/ not found, created empty structure${NC}"
fi

# Clean stale DB from previous install (fresh start)
rm -f "$OPENRY_HOME/openry.db" "$OPENRY_HOME/openry.db-wal" "$OPENRY_HOME/openry.db-shm" 2>/dev/null || true
echo ""

# ── 9. Verify ────────────────────────────────────────────────────────────

echo -e "  Verifying openry..."
if openry -c 'echo "install OK"' 2>/dev/null | grep -q "install OK"; then
    OPENRY_BIN=$(which openry 2>/dev/null || echo "$WRAPPER_BIN/openry")
    echo -e "  ${GREEN}✓ openry is ready${NC}  (${CYAN}${OPENRY_BIN}${NC})"
else
    echo -e "  ${RED}✗ Verification failed${NC}"
    echo "  Try: cd $SCRIPT_DIR && PYTHONPATH=. $PYTHON -m openry -c 'echo test'"
    exit 1
fi
echo ""

# ── 10. orchestrator-plugin (conditional) ─────────────────────────────────

if [ "$SKIP_PLUGIN" = true ]; then
    echo -e "  ${YELLOW}⚠ Skipping orchestrator plugin (--skip-plugin)${NC}"
    echo ""
else

PLUGIN_DIR="${SCRIPT_DIR}/orchestrator-plugin"
if [ -d "$PLUGIN_DIR" ]; then
    echo -e "${BOLD}── Orchestrator Plugin (OpenClaw integration) ──${NC}"
    echo ""

    MISSING_DEPS=""
    command -v openclaw &>/dev/null || MISSING_DEPS="${MISSING_DEPS}  - OpenClaw not found (install: https://openclaw.ai)\n"
    command -v node &>/dev/null || MISSING_DEPS="${MISSING_DEPS}  - Node.js not found (install: https://nodejs.org)\n"
    command -v npm &>/dev/null || MISSING_DEPS="${MISSING_DEPS}  - npm not found (bundled with Node.js)\n"

    if [ -n "$MISSING_DEPS" ]; then
        echo -e "  ${YELLOW}⚠ Skipping orchestrator plugin:${NC}"
        echo -e "$MISSING_DEPS"
        echo "  Re-run this installer after installing the missing dependencies."
    else
        echo -e "  ${GREEN}✓${NC} OpenClaw + Node.js detected, installing plugin..."
        PLUGIN_OK=true

        cd "$PLUGIN_DIR"

        # ── Fast path: use pre-built bundle if available ──
        BUNDLE_FILE="orchestrator-plugin-bundle.tar.gz"
        BUNDLE_LOCAL="${SCRIPT_DIR}/deps/macos/${BUNDLE_FILE}"
        BUNDLE_VERSION="plugin-bundle-v1.0"
        USE_BUNDLE=false

        if [ -f "$BUNDLE_LOCAL" ]; then
            echo -e "    Using local plugin bundle: ${BUNDLE_LOCAL}"
            USE_BUNDLE=true
        else
            # Try download from GitHub Release mirror
            BUNDLE_URL="https://ghfast.top/https://github.com/lingopi/openry/releases/download/${BUNDLE_VERSION}/${BUNDLE_FILE}"
            BUNDLE_TMP="/tmp/${BUNDLE_FILE}"
            if curl -fsSL --connect-timeout 30 --max-time 300 -o "$BUNDLE_TMP" "$BUNDLE_URL" 2>/dev/null && [ -f "$BUNDLE_TMP" ]; then
                USE_BUNDLE=true
                BUNDLE_LOCAL="$BUNDLE_TMP"
                # Save to deps/ for future reinstalls
                mkdir -p "${SCRIPT_DIR}/deps/macos"
                cp "$BUNDLE_TMP" "${SCRIPT_DIR}/deps/macos/${BUNDLE_FILE}" 2>/dev/null || true
            fi
        fi

        if [ "$USE_BUNDLE" = true ]; then
            echo -e "    Extracting plugin bundle (standalone, no network needed)..."
            rm -rf "$PLUGIN_DIR/node_modules" "$PLUGIN_DIR/dist" 2>/dev/null || true
            if tar -xzf "$BUNDLE_LOCAL" -C "$PLUGIN_DIR" 2>/dev/null; then
                echo -e "  ${GREEN}✓${NC} Plugin bundle extracted"
            else
                echo -e "  ${YELLOW}⚠ Bundle extraction failed, falling back to npm...${NC}"
                USE_BUNDLE=false
            fi
            # Clean up temp download
            if [ "$BUNDLE_LOCAL" = "/tmp/${BUNDLE_FILE}" ]; then
                rm -f "$BUNDLE_LOCAL" 2>/dev/null
            fi
        fi

        if [ "$USE_BUNDLE" != true ]; then
            # --ignore-scripts: skip better-sqlite3 native module download
            # (which tries GitHub and hangs on poor connectivity)
            npm install --ignore-scripts 2>/dev/null || {
                echo -e "  ${YELLOW}⚠ npm install failed, skipping plugin${NC}"
                PLUGIN_OK=false
            }

            if $PLUGIN_OK; then
                # Download better-sqlite3 prebuilt binary from mirrors
                node scripts/download-native.mjs 2>/dev/null || true
            fi

            if $PLUGIN_OK; then
                npm run build 2>/dev/null || {
                    echo -e "  ${YELLOW}⚠ build failed, skipping plugin${NC}"
                    PLUGIN_OK=false
                }
            fi
        fi

        if $PLUGIN_OK; then
            openclaw plugins install . --link 2>/dev/null || {
                echo -e "  ${YELLOW}⚠ openclaw plugins install failed${NC}"
                echo "    Try: cd $PLUGIN_DIR && openclaw plugins install . --link"
                PLUGIN_OK=false
            }
        fi

        if $PLUGIN_OK; then
            # Agent workspace already seeded from seed/agent-workspace/
            AGENT_WS="${OPENRY_HOME}/agent-workspace"

            echo -e "  ${GREEN}✓${NC} Plugin installed + workspace ready"

            # Register the agent in OpenClaw (idempotent — skips if exists)
            if openclaw agents add openry-worker --workspace "$AGENT_WS" --non-interactive --json >/dev/null 2>&1; then
                echo -e "  ${GREEN}✓${NC} Agent 'openry-worker' registered"

                # Configure agent tools to allow OpenRY plugin tools
                OCL_CONFIG="$HOME/.openclaw/openclaw.json"
                if [ -f "$OCL_CONFIG" ]; then
                    $PYTHON -c "
import json, sys
with open('$OCL_CONFIG', 'r', encoding='utf-8') as f:
    c = json.load(f)
for a in c.get('agents', {}).get('list', []):
    if a.get('id') == 'openry-worker':
        a['tools'] = {
            'profile': 'minimal',
            'alsoAllow': ['openry_run', 'openry_status', 'openry_payload_query', 'openry_knowledge_query']
        }
        break
with open('$OCL_CONFIG', 'w', encoding='utf-8') as f:
    json.dump(c, f, indent=2, ensure_ascii=False)
" 2>/dev/null && echo -e "  ${GREEN}✓${NC} Agent tools configured" || echo -e "  ${YELLOW}⚠${NC} Tools config failed (non-fatal)"
                fi
            else
                echo -e "  ${YELLOW}⚠${NC} Agent registration failed (may already exist)"
            fi

            # ── Install BGE-M3 model (local file or GitHub Release) ──
            echo -e "  Installing BGE-M3 embedding model (one-time, ~400MB)..."
            BGE_VER="bge-m3-v1.0"
            BGE_FILE="bge-m3-offline.tar.gz"
            BGE_LOCAL="${SCRIPT_DIR}/deps/common/${BGE_FILE}"
            BGE_TMP="/tmp/${BGE_FILE}"
            BGE_DIR="/tmp/bge-m3-bundle"
            BGE_OK=false

            if [ -f "$BGE_LOCAL" ]; then
                echo -e "    Using local file: ${BGE_LOCAL}"
                cp "$BGE_LOCAL" "$BGE_TMP" && BGE_OK=true
            else
                BGE_URL="https://ghfast.top/https://github.com/lingopi/openry/releases/download/${BGE_VER}/${BGE_FILE}"
                echo -e "    Downloading from: ${BGE_URL}"
                curl -fsSL --connect-timeout 30 -o "$BGE_TMP" "$BGE_URL" && BGE_OK=true
            fi

            if [ "$BGE_OK" = true ]; then
                rm -rf "$BGE_DIR" 2>/dev/null
                mkdir -p "$BGE_DIR"
                tar -xzf "$BGE_TMP" -C "$BGE_DIR"
                if [ -f "$BGE_DIR/bge-m3-bundle/install-bge-m3.sh" ]; then
                    bash "$BGE_DIR/bge-m3-bundle/install-bge-m3.sh" "$PLUGIN_DIR" && \
                        echo -e "  ${GREEN}✓${NC} BGE-M3 model installed" || \
                        echo -e "  ${YELLOW}⚠${NC} BGE-M3 install script failed"
                fi
                rm -f "$BGE_TMP"
                rm -rf "$BGE_DIR"
            else
                echo -e "  ${YELLOW}⚠${NC} BGE-M3 download failed (will download on first use)"
            fi
            echo ""
            echo -e "  Restart gateway: ${CYAN}openclaw gateway restart${NC}"
        fi

        cd "$SCRIPT_DIR"
    fi
    echo ""
fi
fi  # SKIP_PLUGIN

# ── 11. Done ──────────────────────────────────────────────────────────────

echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║     OpenRY installation complete!                ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}Next steps:${NC}"
echo -e "    1. ${BOLD}openclaw gateway restart${NC}"
echo -e "    2. ${BOLD}openry serve${NC}"
echo "  Then open http://127.0.0.1:\${OPENRY_PORT:-8080}"
echo ""
echo -e "  ${CYAN}Quick test:${NC}"
echo "    openry -c 'echo hello'"
echo ""
echo -e "  ${CYAN}Directories:${NC}"
echo "    Workflows:    ${OPENRY_HOME}/workflows/"
echo "    Compositions: ${OPENRY_HOME}/compositions/"
echo "    Prompts:      ${OPENRY_HOME}/prompts/"
echo "    Prompt Blocks:${OPENRY_HOME}/prompt_blocks/"
echo "    Database:     ${OPENRY_HOME}/openry.db  (auto-created on first use)"
echo ""
